exclude: ".git"

repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
    - id: markdownlint
      stages: [pre-commit]
      args:
        - "docs/*"

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v9.2.0
    hooks:
    - id: cspell
      stages: [pre-commit]
      args: ["-c", "./cspell/cspell.json", "--show-suggestions"]

  - repo: local
    hooks:
    - id: mkdocs-build
      stages: [pre-push]
      name: mkdocs-build
      entry: bash -c 'make build'
      language: system
