    exclude: ".git"

    repos:
      - repo: https://github.com/igorshubovych/markdownlint-cli
        rev: v0.39.0
        hooks:
        - id: markdownlint
          args:
            - "docs/*"

      - repo: https://github.com/streetsidesoftware/cspell-cli
        rev: v8.4.0
        hooks:
          - id: cspell
            args: ["-c", "./cspell/cspell.json", "--show-suggestions"]

      - repo: local
        hooks:
          - id: mkdocs-build
            name: mkdocs-build
            entry: bash -c 'make build'
            language: system
